apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dayplanner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gomo23/dayplanner.git
    targetRevision: main
    path: helm/dayplanner        # ← change from k8s to this
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dayplanner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
